name: build
on: push

jobs:
  buildx:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Build and Publish Image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          tag: ${GITHUB_REF##*/}-${{ steps.package-version.outputs.current-version}},${GITHUB_REF##*/}
          imageName: sylver/micro
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
